export enum PokemonType {
  Normal = "NORMAL",
  Fire = "FIRE",
  Water = "WATER",
  Grass = "GRASS",
  Electric = "ELECTRIC",
  Ice = "ICE",
  Fighting = "FIGHTING",
  Poison = "POISON",
  Ground = "GROUND",
  Flying = "FLYING",
  Psychic = "PSYCHIC",
  Bug = "BUG",
  Rock = "ROCK",
  Ghost = "GHOST",
  Dark = "DARK",
  Dragon = "DRAGON",
  Steel = "STEEL",
  Fairy = "FAIRY",
}
